name: Luke the Guru 
description: "A blog of travel anecdotes and miscellaneous wisdom from Luke the Guru."
markdown: redcarpet
pygments: true
safe: true
lsi: false
timezone: Europe/London
exclude: [Gemfile, Gemfile.lock, README.md]